# Generated by Django 3.2.3 on 2021-06-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=30, null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('file_title', models.TextField(default='')),
                ('file', models.FileField(null=True, upload_to='files/')),
            ],
        ),
    ]
